name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      GO111MODULE: "on"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Build binary
        run: make build
